export const exp_cats = [
  {
    'name': 'Shopping',
    'icon': 'shopping-cart',
    'icon_color': '#000000',
    'bg_color': '#FFC107',
  },
  {
    'name': 'Groceries',
    'icon': 'food-bank',
    'icon_color': '#FFFFFF',
    'bg_color': '#FF5722',
  },
  {
    'name': 'Dining Out',
    'icon': 'restaurant',
    'icon_color': '#FFFFFF',
    'bg_color': '#673AB7',
  },
  {
    'name': 'Home & Utilities',
    'icon': 'home',
    'icon_color': '#000000',
    'bg_color': '#4CAF50',
  },
  {
    'name': 'Travel',
    'icon': 'airplanemode-active',
    'icon_color': '#FFFFFF',
    'bg_color': '#F44336',
  },
  {
    'name': 'Car & Transportation',
    'icon': 'directions-car',
    'icon_color': '#FFFFFF',
    'bg_color': '#9C27B0',
  },
  {
    'name': 'Concerts & Events',
    'icon': 'music-note',
    'icon_color': '#000000',
    'bg_color': '#CDDC39',
  },
  {
    'name': 'Electronics & Gadgets',
    'icon': 'computer',
    'icon_color': '#FFFFFF',
    'bg_color': '#FFEB3B',
  },
  {
    'name': 'Hobbies & Leisure',
    'icon': 'menu-book',
    'icon_color': '#000000',
    'bg_color': '#00BCD4',
  },
  {
    'name': 'Entertainment',
    'icon': 'sports-esports',
    'icon_color': '#FFFFFF',
    'bg_color': '#009688',
  },
  {
    'name': 'Health & Fitness',
    'icon': 'monitor-heart',
    'icon_color': '#FFFFFF',
    'bg_color': '#795548',
  },
  {
    'name': 'Personal Care',
    'icon': 'child-care',
    'icon_color': '#000000',
    'bg_color': '#FF9800',
  },
  {
    'name': 'Education',
    'icon': 'book',
    'icon_color': '#FFFFFF',
    'bg_color': '#607D8B',
  },
  {
    'name': 'Gifts & Donations',
    'icon': 'card-giftcard',
    'icon_color': '#000000',
    'bg_color': '#03A9F4',
  },
  {
    'name': 'Other',
    'icon': 'all-inclusive',
    'icon_color': '#000000',
    'bg_color': '#9b72e3',
  },
];
