export const exp_cats = [
  {
    name: "Car & Transportation",
    en: "Car & Transportation",
    es: "Auto y Transporte",
    fr: "Auto et Transport",
    tr: "Araba ve Ulaşım",
    gr: "Αυτοκίνητο και Μεταφορές",
    it: "Auto e Trasporti",
    ru: "Автомобиль и Транспорт",
    icon: "directions-car",
    icon_color: "#FFFFFF",
    bg_color: "#9C27B0",
  },
  {
    name: "Concerts & Events",
    en: "Concerts & Events",
    es: "Conciertos y Eventos",
    fr: "Concerts et Événements",
    tr: "Konserler ve Etkinlikler",
    gr: "Συναυλίες και Εκδηλώσεις",
    it: "Concerti ed Eventi",
    ru: "Концерты и События",
    icon: "music-note",
    icon_color: "#000000",
    bg_color: "#CDDC39",
  },
  {
    name: "Dining Out",
    en: "Dining Out",
    es: "Comer Fuera",
    fr: "Restaurant",
    tr: "Dışarıda Yemek",
    gr: "Φαγητό Έξω",
    it: "Mangiare Fuori",
    ru: "Питание в Ресторанах",
    icon: "restaurant",
    icon_color: "#FFFFFF",
    bg_color: "#673AB7",
  },
  {
    name: "Education",
    en: "Education",
    es: "Educación",
    fr: "Éducation",
    tr: "Eğitim",
    gr: "Εκπαίδευση",
    it: "Istruzione",
    ru: "Образование",
    icon: "book",
    icon_color: "#FFFFFF",
    bg_color: "#607D8B",
  },
  {
    name: "Electronics & Gadgets",
    en: "Electronics & Gadgets",
    es: "Electrónicos y Gadgets",
    fr: "Électronique et Gadgets",
    tr: "Elektronik ve Aletler",
    gr: "Ηλεκτρονικά και Gadgets",
    it: "Elettronica e Gadget",
    ru: "Электроника и Гаджеты",
    icon: "computer",
    icon_color: "#FFFFFF",
    bg_color: "#FFEB3B",
  },
  {
    name: "Entertainment",
    en: "Entertainment",
    es: "Entretenimiento",
    fr: "Divertissement",
    tr: "Eğlence",
    gr: "Ψυχαγωγία",
    it: "Intrattenimento",
    ru: "Развлечения",
    icon: "sports-esports",
    icon_color: "#FFFFFF",
    bg_color: "#009688",
  },
  {
    name: "Gifts & Donations",
    en: "Gifts & Donations",
    es: "Regalos y Donaciones",
    fr: "Cadeaux et Dons",
    tr: "Hediyeler ve Bağışlar",
    gr: "Δώρα και Δωρεές",
    it: "Regali e Donazioni",
    ru: "Подарки и Пожертвования",
    icon: "card-giftcard",
    icon_color: "#000000",
    bg_color: "#03A9F4",
  },
  {
    name: "Groceries",
    en: "Groceries",
    es: "Comestibles",
    fr: "Épicerie",
    tr: "Market Alışverişi",
    gr: "Παντοπωλείο",
    it: "Generi Alimentari",
    ru: "Продукты",
    icon: "food-bank",
    icon_color: "#FFFFFF",
    bg_color: "#FF5722",
  },
  {
    name: "Health & Fitness",
    en: "Health & Fitness",
    es: "Salud y Fitness",
    fr: "Santé et Fitness",
    tr: "Sağlık ve Fitness",
    gr: "Υγεία και Φυσική Κατάσταση",
    it: "Salute e Fitness",
    ru: "Здоровье и Фитнес",
    icon: "monitor-heart",
    icon_color: "#FFFFFF",
    bg_color: "#795548",
  },
  {
    name: "Hobbies & Leisure",
    en: "Hobbies & Leisure",
    es: "Hobbies y Ocio",
    fr: "Loisirs",
    tr: "Hobiler ve Boş Zaman",
    gr: "Χόμπι και Αναψυχή",
    it: "Hobby e Tempo Libero",
    ru: "Хобби и Досуг",
    icon: "menu-book",
    icon_color: "#000000",
    bg_color: "#00BCD4",
  },
  {
    name: "Home & Utilities",
    en: "Home & Utilities",
    es: "Hogar y Servicios",
    fr: "Maison et Services",
    tr: "Ev ve Faturalar",
    gr: "Σπίτι και Υπηρεσίες",
    it: "Casa e Utenze",
    ru: "Дом и Коммунальные Услуги",
    icon: "home",
    icon_color: "#000000",
    bg_color: "#4CAF50",
  },
  {
    name: "Personal Care",
    en: "Personal Care",
    es: "Cuidado Personal",
    fr: "Soins Personnels",
    tr: "Kişisel Bakım",
    gr: "Προσωπική Φροντίδα",
    it: "Cura Personale",
    ru: "Личный Уход",
    icon: "child-care",
    icon_color: "#000000",
    bg_color: "#FF9800",
  },
  {
    name: "Shopping",
    en: "Shopping",
    es: "Compras",
    fr: "Shopping",
    tr: "Alışveriş",
    gr: "Αγορές",
    it: "Shopping",
    ru: "Покупки",
    icon: "shopping-cart",
    icon_color: "#000000",
    bg_color: "#FFC107",
  },
  {
    name: "Travel",
    en: "Travel",
    es: "Viajes",
    fr: "Voyage",
    tr: "Seyahat",
    gr: "Ταξίδι",
    it: "Viaggi",
    ru: "Путешествия",
    icon: "airplanemode-active",
    icon_color: "#FFFFFF",
    bg_color: "#F44336",
  },
  {
    name: "Other",
    en: "Other",
    es: "Otro",
    fr: "Autre",
    tr: "Diğer",
    gr: "Άλλο",
    it: "Altro",
    ru: "Другое",
    icon: "all-inclusive",
    icon_color: "#000000",
    bg_color: "#9b72e3",
  },
];
