-- Additive restore of friend-to-group invites for the Data API (PGRST205).
-- Safe to re-run: creates missing objects only, grants privileges, reloads PostgREST.
-- Does not drop data. Revert: revoke the grants below and, if this migration
-- created the table, drop public.group_invitations.

create table if not exists public.group_invitations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  sender uuid not null,
  receiver uuid not null,
  group_id bigint not null,
  group_name text
);

comment on table public.group_invitations is 'invite people to access groups';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'group_invitations_pkey'
      and conrelid = 'public.group_invitations'::regclass
  ) then
    alter table public.group_invitations
      add constraint group_invitations_pkey primary key (id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'group_invitations_group_id_fkey'
      and conrelid = 'public.group_invitations'::regclass
  ) then
    alter table public.group_invitations
      add constraint group_invitations_group_id_fkey
      foreign key (group_id) references public.groups(id)
      on update cascade on delete cascade
      not valid;
    alter table public.group_invitations
      validate constraint group_invitations_group_id_fkey;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'group_invitations_receiver_fkey'
      and conrelid = 'public.group_invitations'::regclass
  ) then
    alter table public.group_invitations
      add constraint group_invitations_receiver_fkey
      foreign key (receiver) references public.profiles(id)
      on update cascade on delete cascade
      not valid;
    alter table public.group_invitations
      validate constraint group_invitations_receiver_fkey;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'group_invitations_sender_fkey'
      and conrelid = 'public.group_invitations'::regclass
  ) then
    alter table public.group_invitations
      add constraint group_invitations_sender_fkey
      foreign key (sender) references public.profiles(id)
      on update cascade on delete cascade
      not valid;
    alter table public.group_invitations
      validate constraint group_invitations_sender_fkey;
  end if;
end $$;

create index if not exists group_invitations_group_id_idx
  on public.group_invitations (group_id);

create index if not exists group_invitations_receiver_idx
  on public.group_invitations (receiver);

create index if not exists group_invitations_sender_idx
  on public.group_invitations (sender);

alter table public.group_invitations enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'group_invitations'
      and policyname = 'sender can insert'
  ) then
    create policy "sender can insert"
      on public.group_invitations
      for insert
      to authenticated, anon
      with check (sender = (select auth.uid()));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'group_invitations'
      and policyname = 'sender or receiver can access'
  ) then
    create policy "sender or receiver can access"
      on public.group_invitations
      for select
      to authenticated, anon
      using (
        sender = (select auth.uid())
        or receiver = (select auth.uid())
      );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'group_invitations'
      and policyname = 'sender or receiver can delete'
  ) then
    create policy "sender or receiver can delete"
      on public.group_invitations
      for delete
      to authenticated, anon
      using (
        sender = (select auth.uid())
        or receiver = (select auth.uid())
      );
  end if;
end $$;

grant select, insert, delete on table public.group_invitations to anon;
grant select, insert, delete on table public.group_invitations to authenticated;
grant select, insert, update, delete on table public.group_invitations to service_role;

do $$
begin
  if exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where c.relkind = 'S'
      and n.nspname = 'public'
      and c.relname = 'group_invitations_id_seq'
  ) then
    grant usage, select on sequence public.group_invitations_id_seq to anon;
    grant usage, select on sequence public.group_invitations_id_seq to authenticated;
    grant usage, select on sequence public.group_invitations_id_seq to service_role;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'groups'
      and policyname = 'select_groups_policy'
  ) then
    create policy "select_groups_policy"
      on public.groups
      for select
      to authenticated, anon
      using (
        id in (
          select members.group_id
          from public.members
          where members.profile = (select auth.uid())
        )
        or owner = (select auth.uid())
        or exists (
          select 1
          from public.group_invitations gi
          where gi.receiver = (select auth.uid())
            and gi.group_id = groups.id
        )
      );
  end if;
end $$;

do $$
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'group_invitations'
  ) then
    alter publication supabase_realtime add table only public.group_invitations;
  end if;
end $$;

notify pgrst, 'reload schema';
